<?php

/**
 * @file
 * DH custom module file.
 */

/**
 * Implements hook_block_info().
 */
function dh_custom_block_info() {
  $blocks = array();
  $blocks['trending_news'] = array(
    'info' => t('Trending News'),
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function dh_custom_block_configure($delta = '') {
  $form = array();

  switch ($delta) {
    case 'trending_news':
      // Manual compile option.
      $form['trending_news_manual_compile'] = array(
        '#type' => 'checkbox',
        '#title' => t('Manually Compile Trending News'),
        '#default_value' => variable_get('trending_news_manual_compile', 0),
      );
      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function dh_custom_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'trending_news':
      // Saving the manual compile option.
      variable_set('trending_news_manual_compile', $edit['trending_news_manual_compile']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function dh_custom_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'trending_news':
      $block['content'] = dh_trending_news_block();
      break;
  }

  return $block;
}

/**
 * Function to return the block content.
 */
function dh_trending_news_block() {
  $manual_compile = variable_get('trending_news_manual_compile', 0);
  if ($manual_compile) {
    return views_embed_view('trending_news', 'block_1');
  }
  return views_embed_view('trending_news', 'block');
}
